import Link from "next/link";
import ThemeToggle from "../../../components/ThemeToggle";

export default function OpenEducationProject() {
  return (
    <div className="min-h-screen">
      <ThemeToggle />
      <div className="project-detail-container">
        <Link href="/projects" className="back-button">
          ←
        </Link>

        <div style={{ textAlign: "center" }}>
          <h1 className="project-detail-title">OpenEducation</h1>

          <img
            src="/projects/open-education.svg"
            alt="OpenEducation logo"
            className="project-detail-image"
          />

          <div className="project-detail-description">
            An AI-powered tutoring platform that transforms PDF course materials
            into personalized learning experiences. Students upload course PDFs
            and receive automatically generated diagnostic quizzes to assess
            their existing knowledge.
            <br />
            <br />
            The platform adapts to each learner: students who demonstrate
            mastery on a diagnostic quiz skip ahead, while others receive
            customized learning modules generated by GPT-4. Completion requires
            scoring 100% on a final quiz, ensuring genuine understanding before
            moving on. Voice-enabled tutoring is available through ElevenLabs
            integration.
            <br />
            <br />
            The AI backend runs on an AMD GPU cloud droplet hosting a local
            LLM. Few-shot prompt injection was used to tune and optimize the
            model's response format, ensuring consistent, structured output for
            quiz and module generation.
            <br />
            <br />
            Built with Next.js, Supabase (auth, storage, PostgreSQL), and
            Python for PDF extraction and AI content generation.
          </div>

          <a
            href="https://github.com/Hstrauss1/SmilingUnicorn"
            className="project-link-button"
            target="_blank"
          >
            Project Link
          </a>
        </div>
      </div>
    </div>
  );
}
